AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  URL Shortener Assignment - Java 21

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: java21
    Architectures:
      - x86_64
    Environment:
      Variables:
        TABLE_NAME: !Ref UrlShortenerTable

Resources:
  # 1. The Database
  UrlShortenerTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: shortId
        Type: String

  # 2. The POST Function (Create Short URL)
  CreateUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: url_shortner.CreateUrlHandler::handleRequest
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref UrlShortenerTable
      Events:
        CreateApi:
          Type: Api
          Properties:
            Path: /get-url-shortner
            Method: post

  # 3. The GET Function (Redirect)
  RedirectUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: url_shortner.RedirectUrlHandler::handleRequest
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UrlShortenerTable
      Events:
        RedirectApi:
          Type: Api
          Properties:
            Path: /short/{shortId}
            Method: get

Outputs:
  BaseApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"